# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1c0c4aae2192131a0374ba2b7d0db8603c0c14081e86f389a3f1b3ced1ca4500ad6cf8d9eef2e72c736c770e2f50a779ab579823ce205a8485905f62e78b528

test:
  secret_key_base: 84e414ff2ed5cc1a8d0c9fed20601598c07da7355fbc809bad80f868c879b0991a18add94362ece7dc21c49ec01c73d81dc4a50bba92c596e958c7ca602eb1ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
